name: Update formula

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened

jobs:

  build:
    name: Update formula
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up tap
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          brew tap nicholasdille/tap https://${HOMEBREW_GITHUB_API_TOKEN}@github.com/nicholasdille/homebrew-tap

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master
      
      - name: Check token
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          test -n "${HOMEBREW_GITHUB_API_TOKEN}"
      
      - name: Check git config
        run: |
          git config --list
      
      - name: Foo
        run: |
          printenv | sort

      - name: Update formula
        id: update-formula
        env:
          PR: ${{ github.event.pull_request.number }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        run: |
          echo "Running for PR #${PR}"

          FILES=$(
              curl "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR}/files" \
                      --silent \
                      --location \
                      --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
                  jq --raw-output '.[].filename'
          )
          STARTS_WITH="scripts/"
          for FILE in ${FILES}; do
              if test "${FILE:0:${#STARTS_WITH}}" == "${STARTS_WITH}"; then
                  echo "Updating ${FILE}"
                  bash "${FILE}" --strict --no-browse --no-fork --message="Opened by ${GITHUB_REPOSITORY}#${PR}"
              fi
          done
